import pyautogui
import time 

pyautogui.PAUSE = 1
pyautogui.press('Win')
pyautogui.write('Chrome')
#time.sleep(1)
pyautogui.press('Enter')
#time.sleep(1)
url = 'https://www.google.com/'
pyautogui.write(url)
pyautogui.press('Enter')
#time.sleep(1)
pyautogui.write('Senai')
pyautogui.press('Enter')
pyautogui.press('F11')
# pyautogui.click(x=324, y=111)
pyautogui.press('Tab', presses=15)
pyautogui.press('Enter')
pyautogui.press('Tab', presses=46)
pyautogui.press('Enter')
pyautogui.rightClick(x=1509, y=459)
pyautogui.press('down', presses=9)
pyautogui.press('Enter')
pyautogui.hotkey('Win', 'd')
pyautogui.rightClick()
pyautogui.press('down', presses=11)
pyautogui.press('right')
pyautogui.press('Enter')
pyautogui.write('Foto_senai')
pyautogui.press('Enter')
pyautogui.press('Win')
pyautogui.write('Word')
pyautogui.press('Enter')
time.sleep(3)
pyautogui.press('Enter')
#pyautogui.click(1064,532)
pyautogui.hotkey('ctrl', 'v')
pyautogui.hotkey('alt', 'F4')
pyautogui.press('Enter')
pyautogui.write('SenaiDaMassa')
pyautogui.click(478,50)
caminho = r'C:\Users\Aluno\Desktop\Foto_senai'
pyautogui.write(caminho)
pyautogui.press('Enter')
pyautogui.press('tab', presses=14)
pyautogui.press('Enter')